version: '3.8'

services:
  dcbot:
    image: izumi-dcbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dcbot-app-izumi
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - DATABASE_URL=${DATABASE_URL}
      - MEMCACHED_HOST=memcached:11211
      - OPENAI_KEY=${OPENAI_KEY}
      - TENOR_API_KEY=${TENOR_API_KEY}
      - NODE_ENV=production
    networks:
      - network_1
    depends_on:
      memcached:
        condition: service_started
    volumes:
      - dcbot-logs-volume:${APP_WORKDIR}/logs:rw

  memcached:
    image: memcached:alpine
    container_name: dcbot-memcached
    networks:
      - network_1
    command: -m 128


volumes:
  dcbot-logs-volume:

networks:
  network_1:
    ipam:
      driver: default
      config:
        - subnet: "20.20.20.128/25"